apiVersion: v1
kind: Service
metadata:
  name: ai-forgestream-api-service
  namespace: ai-forgestream
spec:
  type: LoadBalancer
  selector:
    app: ai-forgestream-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
